services:
  streamlit:
    build:
      context: .  # Path to the directory with the Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"  
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./logs:/app/logs 
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0  # Make Streamlit listen on all interfaces
    restart: unless-stopped 

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  
    networks:
      - backend
    depends_on:
      - streamlit  
    restart: unless-stopped
      
networks:
  backend:
    driver: bridge
