services:
  app:
    build:
      context: .  
    container_name: app
    ports:
      - "8501:8501"  
    networks:
      - backend
    volumes:
      - ./logs:/app/logs 
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped 

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  
    networks:
      - backend
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
      
networks:
  backend:
    driver: bridge
